# Dev api server
DOMINIO="http://localhost:5000/"

# OpenAI 
OPENAI_API_KEY="your-api-openai"
OPENAI_MODEL_35="openai_model_name"
OPENAI_MODEL="openai_model_name"


# Secret JWT
SECRET_KEY="your-secret_jwt"

# Helicone Keys
HELICONE_AUTH="your-bearer-helicone-key"
HELICONE_SESSION="Dev"
HELICONE_API_KEY="your-api-helicone-key"

# Database MongoDB
MONGO_URI="mongodb+srv://your-mongodb-database"

# Lakera Guard
LAKERA_API="your-api-lakera"

# Users for the app
[passwords]
admin = "admin"
user = "user"